-- ═══════════════════════════════════════════════════════════════
-- DATOS DE EJEMPLO (demo): las 17 organizaciones ficticias que traía
-- el prototipo original (antes de conectar Supabase), para poblar el
-- directorio con contenido de muestra. No están asociadas a ningún
-- usuario real (uid = NULL): un admin puede editarlas o borrarlas
-- desde el panel Admin, pero ningún usuario común puede 'reclamarlas'
-- como propias (el trigger de sql/001 bloquea cambiar empresas.uid).
--
-- Correr una sola vez en el SQL Editor de Supabase. Es idempotente:
-- si el CUIT ya existe, el INSERT de esa fila se ignora.
-- ═══════════════════════════════════════════════════════════════

insert into public.empresas
  (uid, cuit, tipo, nombre, sector, calle, ciudad, provincia, pais, referente, cargo, email_org, tel, web, descripcion, logo, ofertas, instalaciones, needs_uncovered, needs_covered)
values
  (NULL, '30-71000001-9', 'Empresa', 'Kioshi Footwear', 'Calzado deportivo', 'Gral. José María Paz 1885', '9 de Abril', 'Buenos Aires', 'Argentina', 'Fernando Bossia', 'Director', NULL, '+54 11 5463-5871', 'https://kioshifootwear.com.ar', 'Empresa de calzado deportivo fundada en 2016, radicada en el Partido de Esteban Echeverría.', NULL, ARRAY['Calzado deportivo','Diseño de calzado','Producción de calzado'], ARRAY['Planta de producción industrial'], ARRAY['Materiales técnicos para calzado','Control de calidad industrial'], ARRAY['Distribución y logística']),
  (NULL, '30-71000002-9', 'Empresa', 'Tulsa TTI', 'Oil & Gas', 'San Pedro 986', 'Villa Lynch', 'Buenos Aires', 'Argentina', 'Natalio Calusic', 'Socio', 'ventas@tulsaoil.com', '+54 11 4753-6222', 'https://tulsaoil.com', 'Empresa PyME argentina de ingeniería aplicada a la industria petrolera. Diseño y fabricación de cabezales y soluciones de subsuelo para Oil & Gas.', NULL, ARRAY['Servicios para Oil & Gas','Equipos para Oil & Gas','Cabezales de pozo','Mantenimiento de equipos'], ARRAY['Taller de manufactura'], ARRAY['Ingeniería de materiales','Inspección de tuberías'], ARRAY['Logística de campo']),
  (NULL, '30-71000003-9', 'Emprendedor/Egresado', 'Colegio de Ingenieros Prov. Bs. As.', 'Institución profesional', 'Calle 9 Nro. 1111', 'La Plata', 'Buenos Aires', 'Argentina', 'Leandro Campos', 'Tesorero', NULL, NULL, NULL, 'Institución que agrupa y representa a los ingenieros de la Provincia de Buenos Aires.', NULL, ARRAY['Representación profesional','Networking entre ingenieros','Capacitación continua'], ARRAY['Sede institucional'], ARRAY['Digitalización de trámites','Plataforma de vinculación empresarial'], ARRAY['Asesoría legal']),
  (NULL, '30-71000004-9', 'Empresa', 'Tecmatik', 'Transmisión mecánica', 'Pje. Cuba 751', 'Avellaneda', 'Buenos Aires', 'Argentina', 'Marcelo Chindemi', 'Director', 'info@tekmatic.com.ar', '+54 11 4222-5040', NULL, 'Empresa especializada en embragues industriales y transmisión de potencia mecánica. Más de 54 años de experiencia.', NULL, ARRAY['Embragues industriales','Transmisión de potencia','Frenos industriales'], ARRAY['Planta de manufactura industrial'], ARRAY['Ensayos de materiales','Tratamientos superficiales'], ARRAY['Mecanizado de piezas']),
  (NULL, '30-71000005-9', 'Empresa', 'Argentec', 'Herramientas eléctricas', NULL, 'Buenos Aires', 'Buenos Aires', 'Argentina', 'Sergio D''Agostin', 'Director', NULL, NULL, NULL, 'Fabricación y comercialización de herramientas eléctricas de mano para el mercado industrial.', NULL, ARRAY['Herramientas eléctricas de mano','Servicio técnico'], ARRAY['Planta de ensamble'], ARRAY['Desarrollo de nuevos materiales','Ensayos eléctricos y de seguridad'], ARRAY['Distribución nacional']),
  (NULL, '30-71000006-9', 'Empresa', 'IMDESA', 'Microfusión', NULL, 'Buenos Aires', 'Buenos Aires', 'Argentina', 'Sergio D''Agostin', 'Director', NULL, NULL, NULL, 'Empresa dedicada a la microfusión de piezas metálicas de alta precisión por método de cera perdida.', NULL, ARRAY['Microfusión de metales','Piezas de precisión','Fundición por cera perdida'], ARRAY['Horno de fundición'], ARRAY['Análisis metalográfico','Diseño de moldes avanzados'], ARRAY['Insumos de fundición']),
  (NULL, '30-71000007-9', 'Empresa', 'Greenworking', 'Oil & Gas / Minería', NULL, 'Comodoro Rivadavia', 'Chubut', 'Argentina', 'Walter Di Benedetto', 'Gerente', NULL, NULL, NULL, 'Empresa de servicios especializados para Oil & Gas y minería en la Patagonia.', NULL, ARRAY['Servicios para Oil & Gas','Servicios para minería','Consultoría operativa'], ARRAY['Equipamiento de campo'], ARRAY['Inspección de tuberías','Monitoreo ambiental'], ARRAY['Personal técnico']),
  (NULL, '30-71000008-9', 'Emprendedor/Egresado', 'Consultoría Radicación Industrial', 'Consultoría', NULL, 'Buenos Aires', 'Buenos Aires', 'Argentina', 'Claudio Galli', 'Consultor', NULL, NULL, NULL, 'Consultoría especializada en radicación y habilitación industrial.', NULL, ARRAY['Radicación industrial','Gestión de habilitaciones','Asesoría regulatoria'], '{}', ARRAY['Plataforma de gestión de proyectos','Digitalización de procesos'], ARRAY['Asesoría legal']),
  (NULL, '30-71000009-9', 'Empresa', 'Locane Hnos S.R.L.', 'Autopartista', 'Gral. O''Higgins 364', 'Lanús Este', 'Buenos Aires', 'Argentina', 'Diego Locane', 'Socio', NULL, NULL, NULL, 'Empresa autopartista fabricante de componentes de tren delantero: extremos, rótulas, barras y brazos.', NULL, ARRAY['Autopartes','Mecanizado de piezas','Suspensión y dirección automotriz'], ARRAY['Planta de mecanizado CNC'], ARRAY['Ensayos de resistencia de materiales','Certificación IATF'], ARRAY['Logística de entrega']),
  (NULL, '30-71000010-9', 'Empresa', 'Kioshi Transformadores', 'Electrotecnia', NULL, 'Lomas de Zamora', 'Buenos Aires', 'Argentina', 'Julián Moreno', 'Director / Pte. APYME', NULL, NULL, NULL, 'Empresa fabricante de transformadores eléctricos.', NULL, ARRAY['Transformadores eléctricos','Diseño eléctrico'], ARRAY['Planta de bobinado'], ARRAY['Ensayos eléctricos y de seguridad','Aislantes eléctricos especiales'], ARRAY['Cobre para bobinado']),
  (NULL, '30-71000011-9', 'Empresa', 'FABINSA S.R.L.', 'Insumos sanitarios', NULL, 'Mar del Plata', 'Buenos Aires', 'Argentina', 'Ariel Palumbo', 'Socio', NULL, NULL, NULL, 'Empresa de fabricación y comercialización de insumos sanitarios.', NULL, ARRAY['Insumos sanitarios','Distribución de materiales sanitarios'], ARRAY['Depósito y logística'], ARRAY['Control de calidad de materiales','Certificaciones sanitarias'], ARRAY['Importación de insumos']),
  (NULL, '30-71000012-9', 'Empresa', 'STRAPLAS S.A.', 'Materiales compuestos – PRFV', NULL, 'Mendoza', 'Mendoza', 'Argentina', 'José Strangis', 'Director', NULL, NULL, NULL, 'Empresa fabricante de tanques y postes de Plástico Reforzado con Fibra de Vidrio (PRFV).', NULL, ARRAY['Tanques de PRFV','Postes de PRFV'], ARRAY['Planta de fabricación PRFV'], ARRAY['Ensayos de materiales compuestos','Certificación PRFV'], ARRAY['Fibra de vidrio']),
  (NULL, '30-71000013-9', 'Empresa', 'Vistage Argentina', 'Consultoría – Oil & Gas', NULL, 'Neuquén', 'Neuquén', 'Argentina', 'Diego Stuppia', 'Director', NULL, NULL, NULL, 'Consultora de desarrollo directivo para empresas de Oil & Gas y minería en Neuquén.', NULL, ARRAY['Consultoría para Oil & Gas','Desarrollo directivo'], '{}', ARRAY['Plataforma de gestión de proyectos','Digitalización de procesos'], ARRAY['Capacitación empresarial']),
  (NULL, '30-71000014-9', 'Empresa', 'Ferrocarriles Argentinos S.E.', 'Transporte ferroviario', 'Av. Ramos Mejía 1430', 'Buenos Aires', 'Buenos Aires', 'Argentina', 'Hugo Vallone', 'Gerente General', NULL, NULL, NULL, 'Empresa estatal de transporte ferroviario de Argentina. Sede en Retiro.', NULL, ARRAY['Transporte ferroviario de cargas','Infraestructura ferroviaria'], ARRAY['Red ferroviaria nacional'], ARRAY['Mantenimiento de equipos portuarios','Inspección de tuberías','Mecanizado de piezas'], ARRAY['Mantenimiento de vías']),
  (NULL, '30-71000015-9', 'Empresa', 'Diagnóstico y Soluciones S.A.', 'Ingeniería y mantenimiento industrial', NULL, 'Buenos Aires', 'Buenos Aires', 'Argentina', 'Mariano Zabatta', 'Socio', NULL, NULL, NULL, 'Ingeniería, mantenimiento industrial y outsourcing técnico.', NULL, ARRAY['Mantenimiento industrial','Outsourcing técnico','Diagnóstico de equipos'], ARRAY['Equipos de diagnóstico predictivo'], ARRAY['Análisis metalográfico','Ensayos no destructivos'], ARRAY['Personal técnico']),
  (NULL, '30-71000016-9', 'Empresa', 'Luas Ingeniería', 'Inspección de infraestructura', NULL, 'Rosario', 'Santa Fe', 'Argentina', 'Leonardo Rey', 'Owner', NULL, NULL, NULL, 'Sistemas de video inspección de tuberías para infraestructura y obras civiles.', NULL, ARRAY['Video inspección de tuberías','Diagnóstico de redes cloacales'], ARRAY['Equipos robotizados de inspección'], ARRAY['Software de análisis de imagen','Sensores especializados'], ARRAY['Equipos importados']),
  (NULL, '30-71000017-9', 'Empresa', 'Meraki Supplies and Services S.A.S.', 'Mantenimiento portuario', NULL, 'Buenos Aires', 'Buenos Aires', 'Argentina', 'Luis Solis', 'Socio', NULL, NULL, NULL, 'Mantenimiento de equipos portuarios e insumos para puertos.', NULL, ARRAY['Mantenimiento de equipos portuarios','Servicio técnico portuario'], ARRAY['Taller de mantenimiento portuario'], ARRAY['Metrología dimensional','Ensayos de materiales compuestos'], ARRAY['Insumos técnicos'])
on conflict (cuit) do nothing;
